version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://root:postgres@db:5432/spent-one?sslmode=disable"
    restart: always

  db:
    image: postgres
    container_name: spent-one
    restart: always
    environment:
      POSTGRES_DB: spent-one
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d spent-one"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: